In [101]:
import pandas as pd
import numpy as np
import matplotlib as plt

data1=pd.read_csv(r"C:\Users\Anjishnu Satpathy\Downloads\Week-4-Project\Week-4-Project\fashion-mnist_train.csv")


In [102]:
data1= np.array(data1)
m,n= data1.shape
data_train=data1.T
Y_train=data_train[0]
X_train=data_train[1:n]


In [103]:
Y_train.shape

(60000,)

In [104]:
def init_param():
    W1= np.random.rand(10,784)-0.5
    b1= np.random.rand(10,1)-0.5
    W2= np.random.rand(10,10)-0.5
    b2= np.random.rand(10,1)-0.5
    return W1,b1,W2,b2

def reLU(Z):
    return np.maximum(Z,0)

def softmax(Z):
    return(np.exp(Z - np.max(Z)) / np.exp(Z - np.max(Z)).sum())

def forward_prop(W1,b1,W2,b2,X):
    Z1= W1.dot(X) + b1
    A1= reLU(Z1)
    Z2= W2.dot(A1) + b2
    A2= softmax(Z2)
    return Z1,A1,Z2,A2

def reLU_deriv(Z):
    return Z > 0

#ONEHOTencoder copied code
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(Z1,A1,Z2,A2,W1,W2,X,Y):
    onehot_Y= one_hot(Y)
    dZ2= A2 - onehot_Y
    dW2= 1/m * dZ2.dot(A1.T)
    db2= 1/m * np.sum(dZ2)
    dZ1= W2.T.dot(dZ2) * reLU_deriv(Z1)
    dW1= 1/m * dZ1.dot(X.T)
    db1= 1/m * np.sum(dZ1)
    return dW1,db1,dW2,db2

def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha):
    W1= W1 - alpha*dW1
    b1= b1 - alpha*db1
    W2= W2 - alpha*dW2
    b2= b2 - alpha*db2
    return W1,b1,W2,b2
    

In [105]:
def gradient_descent(X,Y,alpha,iterations):
    W1,b1,W2,b2 = init_param()
    for i in range(iterations):
        Z1,A1,Z2,A2 = forward_prop(W1,b1,W2,b2,X)
        dW1,db1,dW2,db2 = back_prop(Z1,A1,Z2,A2,W1,W2,X,Y)
        W1,b1,W2,b2 = update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha)
        if i % 10==0: 
            print("Iteration: ", i)
            prediction = get_predictions(A2)
            print(get_accuracy(prediction,Y))
    return W1,b1,W2,b2

def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size        

In [106]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[0 0 0 ... 0 0 0] [2 9 6 ... 8 8 7]
0.09996666666666666
Iteration:  10
[0 0 0 ... 0 0 0] [2 9 6 ... 8 8 7]
0.1
Iteration:  20
[0 0 0 ... 0 0 0] [2 9 6 ... 8 8 7]
0.1


KeyboardInterrupt: 